[project]
name = "puzzles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.8.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "polars>=1.37.1",
]
